### ISSUE TITLE
Beginner question: Why configure tailwindcss like this vs official docs?

### ISSUE THREAD

**Issue by swartchris8** [jarraga/vite-vue3-template#1]
First of all thanks for sharing this template! It's the first project where I could get the vue router working easily.

I am a complete JS beginner so apologies if this question is a simple one.

I noticed you use tailwind purge in `tailwind.config.js` and seem to literally define the tailwind properties in `Butt.vue`
What are the benefits of doing this vs the official docs where tailwind can enrich all of the template files:

```
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by jarraga** [comment]
Hi @swartchris8! thanks for your question, they are all important!
This tailwind configuration is old, unfortunately I don't have time to update the repo. Previously the "content" property was called "purge", since version 3.0 it change its name to something more intuitive
[migration](https://tailwindcss.com/docs/upgrade-guide#configure-content-sources)

On the other hand, all the classes declared in the Button component are necessary precisely so that tailwind includes them in the generated css. Tw is a development tool that generates the classes during compilation, and not at runtime.
I leave you a reference:
[dynamic-class-names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)

Greetings!

**Comment by swartchris8** [comment]
Thanks for the helpful answer 🙂
